# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa364a79707086a40553de297a16ca7d0ad5b9f7b5d9d9b82c07000730a3af7d2beb5735c7b828b010756158cf6b0cb54c4e9bc6d47c5ebcdffb995d254883e8

test:
  secret_key_base: 54dec3600c71e5e1910cff40b82834c68a5e3a9e997cc1895332af6fdc4f07ab1eea6042df96cab45e42fa1b35196ef4307f3989a069f647522db716a99e7669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
