class AppLabConstants
	HEADERSTART 			= "/* headers starts here */\n"
	HEADEREND 				= "/* headers end here */ \n"
	CLASSDECLRATIONSTART 	= "/* class declaration start here */\n"
	CLASSDECLRATIONEND		= "/* class declaration ends here */\n"
	VARIABLEDECLRATIONSTART = "/* variable declarations */\n"
	VARIABLEDECLRATIONEND	= "/* variable declarations ends here */\n"
	CLASS 					= "class "
	EXTENDS					= " extends "
	COMPONENTS				= "Components "
	BRACKETOPEN				= "("
	BRACKETCLOSE			= ")"
	CURLBRACKETOPEN			= "{"
	CURLBRACKETCLOSE		= "}"
	RENDER					= "render()"
end